# The default RuboCop configuration can be found at
# https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 17

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
